<template>
    <Button :disabled="!enabled" :type="type" @click="onclick">
        <slot>My Button</slot>
    </Button>
</template>
<script>
export default {
    props:{
        model:{
            type:String
        },
        action:{
            type:String
        },
        type:{
            type:String,
            default:'primary'
        }
    },
    data(){
        return {
            enabled:true,
            data1:{}
        }
    },
    methods:{
        onclick:function(){
            alert(JSON.stringify(this.data1));
            this.$axios.post(`/models/${this.model}/${this.action}`,this.data1)
            .then(value=>{
                if(value.success){
                    alert('执行成功！');
                }else{
                    alert(value.message);
                }
            })
            .catch(reason=>{
                alert(reason.message);
            })
        }
    },
    created:function(){
        //接受改变状态的消息
        this.$on('on-enable',state=>{
            this.enabled=state;
        });
        this.$on('SET-POST-DATA',data=>{
            this.data1=data;
        })
    }
}
</script>
